-include Makefile.inc

SHELL := /bin/bash

# The keyword reference is generated by the agent of a release and published
# with it, as keywords-<tag>.tar.gz. The book takes it from there rather than
# running an om binary of its own: a binary built without "make version" names
# a version it is not, and a book generated from it documents a release that
# never existed.
#
#	make kw KEYWORDS_VERSION=v3.1.0        # from the release
#	make kw KEYWORDS_TARBALL=/path/to.tgz  # from a file, to try one out
KEYWORDS_VERSION ?=
KEYWORDS_TARBALL ?=
KEYWORDS_URL ?= https://github.com/opensvc/om3/releases/download/$(KEYWORDS_VERSION)/keywords-$(KEYWORDS_VERSION).tar.gz

KWDIR = src/agent.reference.keywords
KINDS = node cluster svc vol sec cfg usr

.ONESHELL: kw summary changes
.SILENT: kw summary changes

all: summary build

# kw lays the keyword reference of a release into the tracked tree.
#
# It is run when a release is cut, and its result committed: the book then
# builds anywhere, with no agent and no network, and a keyword change arrives
# in a pull request as a diff a reviewer can read.
kw:
	set -e
	tmp=$$(mktemp -d)
	trap "rm -rf $$tmp" EXIT
	if [ -n "$(KEYWORDS_TARBALL)" ]; then
		tar xzf "$(KEYWORDS_TARBALL)" -C $$tmp
	elif [ -n "$(KEYWORDS_VERSION)" ]; then
		curl -sSfL "$(KEYWORDS_URL)" | tar xz -C $$tmp
	else
		echo "KEYWORDS_VERSION=<release tag> or KEYWORDS_TARBALL=<file> is required" >&2
		exit 1
	fi
	src=$$(echo $$tmp/keywords-*)
	# The version the reference documents is the one the agent that generated
	# it reported, and is read from the artifact rather than guessed here.
	version=$$(cat $$src/version)
	rm -rf $(KWDIR)
	mkdir -p $(KWDIR)
	summary="SUMMARY.md.in"
	echo -e "# Agent Keywords Reference ($$version)\n" >$(KWDIR)/$${summary}
	head=$$(pwd)
	for kind in $(KINDS); do
		echo "- [$${kind}](agent.reference.keywords/$${kind}/SUMMARY.md)" >>$(KWDIR)/$${summary}
		mkdir -p $(KWDIR)/$${kind}
		printf "# $${kind}\n\n" >$(KWDIR)/$${kind}/SUMMARY.md
		cd $(KWDIR)/$${kind}
		csplit -q -z $$src/$${kind}.md "/^# /" {*}
		for f in $$(echo xx*); do
			title=$$(head -n1 $$f|cut -d'`' -f2)
			mv $${f} $${title}.md
			echo "  - [$${title}](agent.reference.keywords/$${kind}/$${title}.md)" >>../$${summary}
			echo "- [$${title}]($${title}.md)" >>../$${kind}/SUMMARY.md
		done
		cd $$head
	done
	# The index is the compact corpus the next release computes its changes
	# page from: the rendered pages say what a release has, the index is what
	# two releases are compared through.
	tools/kwindex.py --version "$$version" --out $(KWDIR)/index.json $$src/*.json

# changes writes the page saying what the keywords of this release gained,
# lost and changed, from the index of the release before it.
#
# A binary can only document itself: a keyword removed in this release is
# simply absent from it, and no field of it could say it ever existed. The
# indexes of two releases say it between them.
changes:
	set -e
	if [ -z "$(PREVIOUS_INDEX)" ]; then
		echo "PREVIOUS_INDEX=<path to the index.json of the previous release> is required" >&2
		exit 1
	fi
	version=$$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['version'])" $(KWDIR)/index.json)
	tools/kwdiff.py --from "$(PREVIOUS_INDEX)" --to $(KWDIR)/index.json --out $(KWDIR)/changes.md
	summary="$(KWDIR)/SUMMARY.md.in"
	grep -q "changes.md" $${summary} || sed -i "2a - [Changes in $${version}](agent.reference.keywords/changes.md)" $${summary}

summary:
	cat src/preamble/SUMMARY.md.in src/agent/SUMMARY.md.in src/howtos/SUMMARY.md.in src/appendix/SUMMARY.md.in src/agent.reference.keywords/SUMMARY.md.in > src/SUMMARY.md

build:
	mdbook build
